# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Archival Archetyping
email: archival-archetyping-info@group.iamas.ac.jp
description: >- # this means to ignore newlines until "baseurl:"
  The website of the Archival Archetyping.
  Archival Archetyping is a research project since 2019 at the Institute of Advanced Media Arts and Sciences [IAMAS].
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://archival-archetyping.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iamas_aa
github_username: archival-archetyping

# Build settings
markdown: kramdown
repository: "mmistakes/minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "default"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

search: true
search_provider: "google"
google:
  search_engine_id: "80daa649bece7db55"
google_site_verification: "17Jq8kMxZQyDMx_KY4Jea7P_-XiVsPnbrHyxkPVEOpU"

share: true
og_image: /assets/images/the-morandi-room.jpg

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      share: true
      related: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-BSS0BNPBCM"
    anonymize_ip: false # default

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/iamas_aa"